---
title: configure-power-control
description: configure-power-control
privilege: TrustedInstaller
actions:

  # === Disable Hibernate via revitool
  # ------> Disabling hibernate improves system stability, fixes dual-boot and upgrade issues, and frees up disk space
  # ------> NOTE: It can cause overheating in sleep mode.
  - !run:
    path: "%ProgramFiles%\\Revision Tool"
    exe: "revitool.exe"
    args: "misc hibernate --disable"
    wait: true
    runas: currentUserElevated
    option: disable-hibernate
  - !run:
    path: "%ProgramFiles%\\Revision Tool"
    exe: "revitool.exe"
    args: "misc fast-startup --disable"
    wait: true
    runas: currentUserElevated
    option: disable-hibernate

  # === Enable Hibernate via revitool
  - !run:
    path: "%ProgramFiles%\\Revision Tool"
    exe: "revitool.exe"
    args: "misc hibernate --enable"
    wait: true
    runas: currentUserElevated
    option: enable-hibernate
  - !run:
    path: "%ProgramFiles%\\Revision Tool"
    exe: "revitool.exe"
    args: "misc fast-startup --enable"
    wait: true
    runas: currentUserElevated
    option: enable-hibernate

  # === Shutdown Menu - Sleep - Enabled
  # ------> https://www.tenforums.com/tutorials/7445-add-remove-hibernate-power-menu-windows-10-a.html
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings', value: 'ShowSleepOption', type: REG_DWORD, data: '1'}

  # === Allow system to be shut down without having to log on - Enabled
  # ------> https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/shutdown-allow-system-to-be-shut-down-without-having-to-log-on
  # ------> https://www.stigviewer.com/stig/windows_server_2012_member_server/2014-01-07/finding/V-1075
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'ShutdownWithoutLogon', type: REG_DWORD, data: '1'}
