---
title: Configuration
description: Applies some Revision configurations
privilege: TrustedInstaller
actions:

  # Disable Memory Compression
  - !powerShell: 
    command: 'Disable-MMAgent -mc'

  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Services\Pending\7971f918-a847-4430-9279-4a52d1efe18d', value: 'RegisterWithAU', type: REG_DWORD, data: '0'}

  - !cmd:
    command: 'setx DOTNET_CLI_TELEMETRY_OPTOUT 1'
    runas: currentUserElevated
    
  - !cmd:
    command: 'setx POWERSHELL_TELEMETRY_OPTOUT 1'
    runas: currentUserElevated

  - !writeStatus: {status: "Removing logs"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File CLEANER.ps1'
    weight: 150

  - !writeStatus: {status: "Finalizing process"}
  - !registryValue: {path: 'HKCU\System\GameConfigStore', value: 'GameDVR_FSEBehaviorMode', type: REG_DWORD, data: '0', weight: 70}

  - !powerShell: {command: 'Get-ScheduledTask -TaskPath "\Microsoft\Office\*" | Disable-ScheduledTask'}

  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File SVCGROUP.ps1'
    weight: 50

  - !run: {exeDir: true, exe: "FINALIZE.cmd", weight: 200}

  - !run:
    exeDir: true
    exe: "STARTMENU.cmd"
    option: "remove-pinned-items-startmenu"
    weight: 100

  - !run:
    exeDir: true
    exe: "FILEASSOC.cmd"
    option: "remove-appx-photos"
    weight: 150

  - !cmd:
    exeDir: true
    command: 'robocopy "Wallpapers" "%systemroot%\Web\Wallpaper\MeetRevision\v2" /E /PURGE /IM /IT /NP'
    ignoreErrors: true

  - !powerShell:
    command: '.\WALLPAPER.ps1 -Mode Desktop -ImagePath $env:systemroot\Web\Wallpaper\MeetRevision\v2\desktop.jpg'
    exeDir: true
    runas: currentUserElevated
    option: "configure-wallpaper"
    weight: 45

  - !powerShell: 
    command: '.\WALLPAPER.ps1 -Mode LockScreen -ImagePath $env:systemroot\Web\Wallpaper\MeetRevision\v2\lockscreen.jpg'
    exeDir: true
    runas: currentUserElevated
    option: "configure-wallpaper"
    weight: 45

  - !powerShell:
    command: 'Copy-Item -Path .\WALLPAPER.ps1 -Destination "$env:systemroot\Web\Wallpaper\MeetRevision" -Force'
    exeDir: true
    option: "configure-wallpaper"
  
  - !powerShell:
    command: 'Copy-Item -Path .\WallpaperStartup.cmd -Destination "$env:systemroot\Web\Wallpaper\MeetRevision" -Force'
    exeDir: true
    option: "configure-wallpaper"

  - !powerShell:
    command: '.\Set-Theme.ps1 -WallpaperPath "$env:SystemRoot\Web\Wallpaper\MeetRevision\v2\desktop.jpg" -ThemeExportPath "$env:SystemRoot\Resources\Themes\revi.theme" -SystemMode "Dark" -AppMode "Dark"'
    exeDir: true
    runas: currentUserElevated
    options: ["configure-wallpaper", "configure-darkmode"]
  
  - !powerShell:
    command: '.\Set-Theme.ps1 -WallpaperPath "$env:SystemRoot\Web\Wallpaper\MeetRevision\v2\desktop.jpg" -ThemeExportPath "$env:SystemRoot\Resources\Themes\revi.theme" -SystemMode "Light" -AppMode "Light"'
    exeDir: true
    runas: currentUserElevated
    options: ["configure-wallpaper", "!configure-darkmode"]


  # Still necessary to set for W10
  ## if dark mode is deselected, then revert to light mode
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'AppsUseLightTheme', type: REG_DWORD, data: '0', option: "configure-darkmode", weight: 70}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'SystemUsesLightTheme', type: REG_DWORD, data: '0', option: "configure-darkmode", weight: 50}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'AppsUseLightTheme', type: REG_DWORD, data: '1', option: "!configure-darkmode", weight: 70}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'SystemUsesLightTheme', type: REG_DWORD, data: '1', option: "!configure-darkmode", weight: 50}


  - !registryValue: 
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'
    value: 'RevisionWallpaperStartup'
    type: REG_SZ
    oobe: only
    data: 'cmd /c "%SystemRoot%\Web\Wallpaper\MeetRevision\WallpaperStartup.cmd"'

  # Necessary to refresh start menu entries etc.
  - !appx: {operation: clearCache, name: '*Client.CBS*'}
  - !appx: {operation: clearCache, name: '*StartMenuExperienceHost*', option: "remove-pinned-items-startmenu"}
  - !appx: {operation: clearCache, name: '*Windows.Search*'}
  - !appx: {operation: clearCache, name: '*TCUI*'}

  # Force update group policy
  - !run: 
    exe: "gpupdate.exe"

  # Apply micro patches via Revision Tool in order to avoid new playbook releases for minor changes
  - !run:
    path: "%ProgramFiles%\\Revision Tool"
    exe: "revitool.exe"
    args: "playbook-patches apply"
    wait: true
    runas: currentUserElevated
    
  - !powerShell:
    command: |
      $explorerProcess = Get-Process -Name explorer -ErrorAction SilentlyContinue
      if ($explorerProcess) {
        Stop-Process -Name explorer -Force
      }
      Start-Process explorer
    runas: currentUserElevated
