---
title: Remove Win32 apps
description: Removal of Win32 apps
privilege: TrustedInstaller
actions:

  # Microsoft Edge
  - !writeStatus: {status: "Removing MS Edge", option: "remove-edge"}
  - !taskKill: {name: "MicrosoftEdgeUpdate", errorAction: Ignore, option: "remove-edge"}
  - !taskKill: {name: "msedge", errorAction: Ignore, option: "remove-edge"}
  - !taskKill: {name: "MicrosoftEdge*", errorAction: Ignore, option: "remove-edge"}
  - !taskKill: {name: "setup", errorAction: Ignore, pathContains: "\\Edge", option: "remove-edge"}

  # Setting device region to US (244) allows uninstallation without known parent processes
  - !powerShell:
    command: '.\EDGE.ps1 -Mode SetDeviceRegion -DeviceRegion 244'
    exeDir: true
    option: "remove-edge"

  - !powerShell:
    command: '.\EDGE.ps1 -Mode EdgeBrowser'
    exeDir: true
    runas: currentUserElevated
    option: "remove-edge"
    weight: 40

  - !powerShell:
    command: '.\EDGE.ps1 -Mode RestoreDeviceRegion'
    exeDir: true
    option: "remove-edge"

  - !powerShell:
    option: "remove-edge"
    exeDir: true
    errorAction: Ignore
    weight: 30
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'Microsoft.MicrosoftEdge',
        'Microsoft.MicrosoftEdgeDevToolsClient',
        'Microsoft.Edge.GameAssist'
      )
  
  # In case Revision Tool's removal method fails
  - !powerShell:
    option: 'remove-winsxs-ai'
    exeDir: true
    errorAction: Ignore
    weight: 30
    command: >-
      .\APPX-REMOVER.ps1 -Packages 'Microsoft.Copilot'

  # OneDrive
  - !writeStatus: {status: "Removing OneDrive", option: "remove-onedrive"}
  - !taskKill: {name: "OneDriveStandaloneUpdater", errorAction: Ignore, option: "remove-onedrive"}
  - !taskKill: {name: "OneDriveSetup", errorAction: Ignore, option: "remove-onedrive"}
  - !taskKill: {name: "OneDrive*", errorAction: Ignore, option: "remove-onedrive"}

  - !run: {exeDir: true, exe: "ONED.cmd", option: "remove-onedrive", oobe: false, iso: false, weight: 40}
  - !file: {path: "%SystemDrive%\\OneDriveTemp", option: "remove-onedrive"}
  - !file: {path: "%ProgramData%\\Microsoft OneDrive", option: "remove-onedrive"}

  - !powerShell:
    option: "remove-onedrive"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'OneDrive',
        'microsoft.microsoftskydrive'
      )

  # Teams
  - !writeStatus: {status: "Removing Teams", option: "remove-teams"}
  - !taskKill: {name: "Teams", errorAction: Ignore, option: "remove-teams"}
  - !taskKill: {name: "Update", errorAction: Ignore, option: "remove-teams"}
  - !taskKill: {name: "ms-teamsupdate", errorAction: Ignore, option: "remove-teams"}

  - !powerShell:
    option: "remove-teams"
    wait: true
    exeDir: true
    errorAction: Ignore
    weight: 10
    command: >-
      .\APPX-REMOVER.ps1 -Packages @(
        'MicrosoftTeams',
        'MSTeams', # New Teams
        'Flipgrid'
      )
  
  # Microsoft Teams Meeting Add-in for Microsoft Office
  - !run:
    option: "remove-teams"
    wait: true
    exe: "msiexec.exe"
    args: "/qn /norestart /X{A7AB73A3-CB10-4AA5-9D38-6AEFFBDE4C91}"
    weight: 10
    showError: false
    runas: currentUserElevated

  # === Prevent automatic Teams installation
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Communications', value: 'ConfigureChatAutoInstall', type: REG_DWORD, data: '0'}