---
title: Configuration
description: Applies some Revision configurations
privilege: TrustedInstaller
actions:

  - !writeStatus: {status: "Configuring general settings"}
  - !registryValue: {path: 'HKCU\System\GameConfigStore', value: 'GameDVR_FSEBehaviorMode', type: REG_DWORD, data: '0', weight: 50}
  - !registryValue: {path: 'HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32', value: '', type: REG_SZ, data: '', weight: 60}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'AppsUseLightTheme', type: REG_DWORD, data: '0', weight: 70}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'SystemUsesLightTheme', type: REG_DWORD, data: '0', weight: 50}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications', value: 'GlobalUserDisabled', type: REG_DWORD, data: '1', weight: 60}
  - !registryValue: {path: 'HKCU\Control Panel\International\User Profile', value: 'HttpAcceptLanguageOptOut', type: REG_DWORD, data: '1', weight: 50}

  - !writeStatus: {status: "Optimizing PowerShell performance"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File ngen.ps1'
    weight: 100

  - !writeStatus: {status: "Finalizing process"}
  - !run: {exeDir: true, exe: "FINALIZE.cmd", weight: 200}

  - !run:
    exeDir: true
    exe: "STARTMENU.cmd"
    weight: 50

  - !run:
    exeDir: true
    exe: "FILEASSOC.cmd"
    weight: 90
  
  - !cmd:
    exeDir: true
    command: 'robocopy "Web" "%windir%\Web" /E /PURGE /IM /IT /NP'
    ignoreErrors: true
    weight: 30

  - !run:
    exeDir: true
    exe: "WALLPAPER.cmd"
    weight: 20

  - !writeStatus: {status: "Removing temporary files"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File CLEANER.ps1'
    weight: 150

  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File DISM-FEATURES.ps1'
    weight: 270

    # Necessary to refresh start menu entries etc.
  - !appx: {operation: clearCache, name: '*Client.CBS*'}
  - !appx: {operation: clearCache, name: '*StartMenuExperienceHost*'}
  - !appx: {operation: clearCache, name: '*Windows.Search*'}

    # Start as user process to prevent weird look due to running as TrustedInstaller
  # - !run: {baseDir: true, exe: "NSudoLC.exe", args: '-U:C -UseCurrentConsole explorer.exe'}