---
title: Configuration
description: Applies some Revision configurations
privilege: TrustedInstaller
actions:

  - !writeStatus: {status: "Configuring general settings"}
  - !registryValue: {path: 'HKCU\System\GameConfigStore', value: 'GameDVR_FSEBehaviorMode', type: REG_DWORD, data: '0', weight: 70}
  - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications', value: 'GlobalUserDisabled', type: REG_DWORD, data: '1', weight: 60}

   # OneDrive workaround
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\OneDrive', value: 'DisableFileSyncNGSC', operation: delete}

  - !writeStatus: {status: "Optimizing PowerShell"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File ngen.ps1'
    weight: 100

  - !writeStatus: {status: "Finalizing process"}
  - !run: {exeDir: true, exe: "FINALIZE.cmd", weight: 200}

  - !run:
    exeDir: true
    exe: "STARTMENU.cmd"
    weight: 100

  - !run:
    exeDir: true
    exe: "FILEASSOC.cmd"
    weight: 150

  - !run:
    exeDir: true
    exe: "WALLPAPER.cmd"
    option: "configure-wallpaper"
    weight: 90

  - !writeStatus: {status: "Removing temporary files"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File CLEANER.ps1'
    weight: 150

  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File DISM-FEATURES.ps1'
    weight: 270

    # Necessary to refresh start menu entries etc.
  - !appx: {operation: clearCache, name: '*Client.CBS*'}
  - !appx: {operation: clearCache, name: '*StartMenuExperienceHost*'}
  - !appx: {operation: clearCache, name: '*Windows.Search*'}

    # Start as user process to prevent weird look due to running as TrustedInstaller
  # - !run: {baseDir: true, exe: "NSudoLC.exe", args: '-U:C -UseCurrentConsole explorer.exe'}