name: Archive and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set file name
        run: echo "FILENAME=Revi-PB-${{ github.ref_name }}.apbx" >> $GITHUB_ENV
      
      - name: Archive content
        run: |
          7z a -p${{ secrets.PASSWORD }} -mhe=on "${{ env.FILENAME }}" ./src/*

      - name: Hash 256
        run: |
          echo "HASH=$(sha256sum ${{ env.FILENAME }} | cut -d ' ' -f 1)" >> $GITHUB_ENV
      
      # - name: DevUploads
      #   run: |
      #     url=$(bash <(curl -s https://devuploads.com/upload.sh) -f "${{ env.FILENAME }}" -k "${{ secrets.DEVUPLOADS_API_KEY }}" | grep -o 'https://devuploads.com[^"]*')
      #     echo "DEVUPLOADS=$url" >> $GITHUB_ENV

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ${{ env.FILENAME }}
          asset_name: ${{ env.FILENAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            # Download Link ✨

            If you would like to support Revision, kindly download the Playbook from the provided link below.

            📌Link: 
            
            SHA256: `${{ env.HASH }}`
            